---
- hosts: all
  pre_tasks:
    - name: Atualizando apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
  roles:
    - dokku_bot.ansible_dokku
    - iac-role-basica
    - iac-role-services
  tasks:
    - name: create app
      dokku_app:
        # change this name in your template!
        app: "{{ app }}"
    - name: environment configuration
      dokku_config:
        app: "{{ app }}"
        config:
          DOKKU_LETSENCRYPT_EMAIL: "{{ dokku_letsencrypt_email }}"
          PORT: "{{ port }}"
          # DATABASE_URL: "{{ database_url }}"
          # CLOUDAMQP_URL: "{{ cloudamqp_url }}"
          # CLOUDAMQP_APIKEY: "{{ cloudamqp_apikey }}"
          CITY_COUNCIL_WEBSERVICE: "{{ city_council_webservice }}"
          DJANGO_ALLOWED_HOSTS: "{{ django_allowed_hosts }}"
          DJANGO_CONFIGURATION: "{{ django_configuration }}"
          # DJANGO_SECRET_KEY: "{{ django_secret_key }}"
          DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
          ENABLE_AUTOTHROTTLE_DEBUG: "{{ enable_autothrottle_debug }}"
          NEW_RELIC_LOG: "{{ new_relic_log }}"
    - name: Add dokku_service network to mariaquiteria
      command: "dokku network:set {{ app }} attach-post-create dokku_services"
      args:
        creates: "/tmp/network_dokku_services_mariaquiteria_{{ env }}"
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
    - name: Configurar o crawl production diário
      ansible.builtin.cron:
        name: "Crawl diario"
        minute: "0"
        hour: "6"
        job: "dokku run dadosabertosdefeira.com.br python manage.py crawl"
