---
- hosts: all
  pre_tasks:
    - name: Atualizando apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
  roles:
    - dokku_bot.ansible_dokku
    - iac-role-basica
    - iac-role-services
  vars:
    dokku_version: 0.22.3
    sshcommand_version: 0.12.0
    dokku_hostname: dadosabertosdefeira.com.br
    dokku_users:
      - name: gomex
        username: gomex
        ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYc9rlj0wKka5t31T4EiTanSmXpswDg00dYmuwdvEW3bAovcdzt6p3kgFxpPaZj7X6oFfvSCXpoL+/yjngujEW9CGbqfdVyvCodIuIaGuoUsxo7dtMCLzqZtGGe1m6xoTyNqZQzv68nF1fZ/ku7YNK9HGKKcjNJVvs6ocqK5Jbdb6IGRF64kP4hx8IX5n8CU8APn5esrh6BNhViKHWYIGDYoFkd54Z4CeD156BYl1OhWbla6u1vOntpj1uw3Lp+haAWbXSJMCpztsYPeynrQ14GUbHPRAsO4IILD5CtZWsp16VnEIAhsIqrnzp1BGTduwbX5VVzY3K7JdFNEWThFhd"
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
  tasks:
    - name: create app
      dokku_app:
        # change this name in your template!
        app: "{{ item.app }}"
      loop: "{{ environments }}"
    - name: environment configuration
      dokku_config:
        app: "{{ item.app }}"
        config:
          DOKKU_LETSENCRYPT_EMAIL: "{{ item.dokku_letsencrypt_email }}"
          PORT: "{{ item.port }}"
          DATABASE_URL: "{{ item.database_url }}"
          CLOUDAMQP_URL: "{{ item.cloudamqp_url }}"
          CLOUDAMQP_APIKEY: "{{ item.cloudamqp_apikey }}"
          CITY_COUNCIL_WEBSERVICE: "{{ item.city_council_webservice }}"
          DJANGO_ALLOWED_HOSTS: "{{ item.django_allowed_hosts }}"
          DJANGO_CONFIGURATION: "{{ item.django_configuration }}"
          DJANGO_SECRET_KEY: "{{ item.django_secret_key }}"
          DJANGO_SETTINGS_MODULE: "{{ item.django_settings_module }}"
          ENABLE_AUTOTHROTTLE_DEBUG: "{{ item.enable_autothrottle_debug }}"
          NEW_RELIC_LOG: "{{ item.new_relic_log }}"
      loop: "{{ environments }}"
    - name: Add dokku_service network to mariaquiteria staging
      command: dokku network:set staging.dadosabertosdefeira.com.br attach-post-create dokku_services
      args:
        creates: /tmp/network_dokku_services_mariaquiteria
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
    - name: Add dokku_service network to mariaquiteria production
      command: dokku network:set dadosabertosdefeira.com.br attach-post-create dokku_services
      args:
        creates: /tmp/network_dokku_services_mariaquiteria
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
    - name: Configurar o crawl production diário
      ansible.builtin.cron:
        name: "Crawl diario"
        minute: "0"
        hour: "6"
        job: "dokku run dadosabertosdefeira.com.br  python manage.py crawl"
