---

# Do galaxy
- src: dokku_bot.ansible_dokku
  version: v2020.11.25

# Do repositório github que tem a role básica
- src: https://github.com/DadosAbertosDeFeira/iac-role-basica.git
  scm: git
  version: "0.1"

# Do repositório github que tem a role service
- src: https://github.com/DadosAbertosDeFeira/iac-role-services.git
  scm: git
  version: "0.1"

# Do galaxy
- src: newrelic.newrelic-infra
  version: "0.8.2"
