galaxy_info:
  author: Dados Abertos de Feira
  description: Role para configurar servidor

  min_ansible_version: 2.10

  platforms:
  - name: Ubuntu
    release: bionic
    versions:
    - all
    - 25

dependencies:
- dokku_bot.ansible_dokku
- geerlingguy.swap
