---
# file: group_vars/production/vars.yml
env: "production"
app: "mq.dadosabertosdefeira.com.br"
# specify a email for dokku-letsencrypt

apps_config:
  DOKKU_LETSENCRYPT_EMAIL: "linux.rafa@gmail.com"
  PORT: "5000"
  # DATABASE_URL: "{{ database_url }}"
  # CLOUDAMQP_URL: "{{ cloudamqp_url }}"
  # CLOUDAMQP_APIKEY: "{{ cloudamqp_apikey }}"
  CITY_COUNCIL_WEBSERVICE: "https://www.transparencia.feiradesantana.ba.leg.br/"
  CITY_COUNCIL_WEBSERVICE_ENDPOINT:   "http://transparencia.feiradesantana.ba.leg.br/webservice"
  DJANGO_ALLOWED_HOSTS: ".mq.dadosabertosdefeira.com.br"
  DJANGO_CONFIGURATION: "Prod"
  DJANGO_SETTINGS_MODULE: "web.settings"
  DOKKU_APP_TYPE: "dockerfile"
  DOKKU_PROXY_PORT: "80"
  DOKKU_PROXY_PORT_MAP: "http:80:5000"
  ENABLE_AUTOTHROTTLE_DEBUG: "true"
  NEW_RELIC_LOG: "stdout"
  SENTRY_ENVIRONMENT: "Prod"
  SPIDERMON_SENTRY_ENVIRONMENT_TYPE: "Prod"
  TIKA_CLIENT_ONLY: "1"
  

# NEWRELIC INFRA
nrinfragent_integrations:
  - { name: nri-nginx, state: "latest" }
  - { name: nri-postgresql, state: "latest" }
nrinfragent_config:
  license_key: "{{ vault_newrelic_key }}"
  log_file: /var/log/newrelic-infra/nr-infra.log
  log_to_stdout: false
