---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
  roles:
    - role: setting-server
